language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: jP64/EqnF5vsDnzZyrzR1pcp1JcgWQIIt1vTM93Hhxe5fVhSkoFZr8JnPEUSubZrKfMvWhSM8nhHxeF143GsHUObypGfx5si67NbIJKR7OaUoU5eFvrMFGJuQ9T/7d3Sr22xOhpTaZFgfb8bmxjT5LSG7mhAMgq/hoUQjp0TSnNHK/utQ7F+C4lyaT5zj98KfWRU8ikDkZ35zz8HHxgQamRjx7ZDypCbLPyPBGdH72BVRvJ/P6KrRqgS/TMoZv9EKdyfTkgsTlkN7Qphwcfc9vLu6XITkIw1GDTqmfws4SYUFqhH6aWbb7mWTRzDH5Ep75s5rbf2LJPQ60D5bgewhKBed7bvcQMHjeiMzxggoWdlltIj84/+Lo5vl7Hm7ts6BsveoCxiJrXC/i0LEC1T85avQtrwroG9Oqmp7pXqCeUoLZ8bE2UMumcgKuzRtH+h205Z+SmsG1+BR2WLeaGyMgFpvrGVUUC4X22J70Uc3wmDZcUsZEYHaEwMFVLkAx1YQNSltIelVW48UZnDva7/EDRgUAC31vAIZmUc3z6TsjC8QrTgj5CnrdK5AmEaoQfUr+qpnLjURVuawJODJM65V0q4337hanKFC9nl8HQH/ScK5BE/LPPlRp+45vRWaGk2sNtU+5sL5xZJFieiDPF+w7fPTMpY5ss8zEV5vfvEqGE=
  on:
    tag: true
    all_branches: true
