language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: ArneTillmann
  password:
    secure: fQIp2PQsmU+cLk71gQFfWb2hw6Z9b9lnl1gtTDgiqlG+UleC72hGFmYlMcRNRhY9zzvipqUdXsVjLgXuwGpuoc89v3SnJVodRbqSPvXAu12oS7acaYTbhUacpdTEtn7HC3pO3WT3hmpGR/tD9pbJo+trA53oNJPtS/IMGBP2cyYjhkBR+rdBh0uTmTj1yqhJhqKVWkeUPjHQTBNfSFjVhmCwXd2CX3fhw0swpfSlS9r80CAPa3WTYUOb6nVrRBsLL0RjxCMjc+NC85Evw7/eq8LOt6eOt5XOOt4nnpZe+bpY1g+bW9lsCs7HgN6AqMytIuLpTXa5uLii6kUDi9xOCsC1DqcZ5A9UynvopAybm+1yezV4IcHA0niDnqkLO6G/l4ZFkltxeHMQUqbqvLq7PJ8L2SML1LvI+F3CHUDaotU5/Ni4v8dy3t6RNRXLtNxPQQFjVyX0u1+pP5Gh4Db5k3uCb1U/wbvy4zBpDpMUeFhY6gj1KcrSyFXnK4wrtcv/QfSLus+Nw9oibum7sV5J6vC26hW5Kxp14Qb9W7wRI7AznRhXPcnIitPjyPZBUwCexGsspACw4cNLpqEn3E7FQ9F7cMYsHyjbhBPUvk47u9x7ITsVLGeANIkO8hUHTgjViIx2WPup2qL4et5vtPKeaLTe9F6J/7fJtUSzTJeiBMk=
  on:
    tag: true
    all_branches: true
