language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: YMhnDwvHB96WyVjSz5+BtLbWJatZbE65UdGc9mOLm20U2CAP3R7yc33UWFUm3MbjLbQTfPtJ725NMnw22BG6jlayKoHMgSnrspwjrx0vcyhxHPI5+/4KOaI59nx05NOJ3ZhL0PNB4ReclmScGHmZNSqCeg+2ZFotC3DWY7hryb6McHO7Ssnt3sVN5u9Ho2hDhLnl1DDwazNQas+qzGSI0C/sj9PsODcZbeZZM9AUpgLPZSqnJozUZOapMkQrdCeJpO8xtSQ5o2UH7tv688Wdv7oczpru9fGhlI6YT3oZW7QbEipCmhjwjtOhitSr0t1/U/X22rrQJwZqhStoddc8rgrT1EvZEjHP2HUZec6w6NXLXMIVp4/lEaRU+t8J7m/4BGo/SCSsQ89L/4WuKFqnwF/vighGw4Bjca1UDA9M3f96xcnnbFkkN+yIR3DrXjEooTuGosM1I4F2f8MF6Xq5qrEO6+mfK5Z2MdO7J655DZJaW4bX91yzKK/eq5Dr7ESi7To9cC8McYLBq5GM4fjCdqcKFCTvCElyOxBMHvdLfRc2WLX0UPjWxx/D5JLRZa87xJ0y6mT/KtM91RfH+pyxwI6yNb+JcXHSX0/kUgirrTRPPqgeRcHMYrYe8+DZGGVzKZjaH2WOIc5i3rvVgrPiU8PZnPBg962VX/1G+G7YYJ8=
  on:
    tag: true
    all_branches: true
