language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ZlHSWIexrkYXzmz6xsEIHjqXa8HPgFxIEeW/MTVDnEoUeNmWgTWcOcDA7Yx1FxodyKFf3dWBZRUConR5XxupDVBMtXZ3WeCKmsUx7rEueI7yyw1w2sTzoH1aqbcbO7AUUm8NlMM91O1ksX4K76NJka1hZvrW2K2pD3Q24CRk2ru8mdvgiidypYCYXWvghgm1SmG5yJfZfJyBPUOaOYBrr73//3TkpIDh+9WBHTVBI97+Q8txtjr9P+MIht1msiqJlQhDnbBOODSygI357KMlvCnqeJgYdCGrCAVJEiNEDchbOIkKEL9kOB2xEtQZFHs/0nZq/UtI6T0+bre+XWMmgNIuvAqNGWXu1K0l8uvlWE1UbszeHVqdqJj4Tlgq+JGJuuOO0/U7lACSRTDk5YJhE76xrJykA+HrUqbErU+mwLQiEdcQNHlbGg5UHgsY2h5hN/YQQ5BPpnffwsOGyf2dyg7N+R/awk2/kUmaE9QEtSgztmWg7rWze3ZfzM6Epw9MerUod0RWmeKdXWfH7O1JTHLqWRu4l3FRkat7CGFrcLLgtuCyb4w+YUokRyYbmcBj56bUq7fcryprNr3C6E/LQSwJD92J7V26syDVsLGQ3Ms0UjdU46/BEMs4TSVs+MK6Q9C+WBt3h9f/qiYv0GffW1EmGBaBXfV2kfLGkwkHLoo=
  on:
    tag: true
    all_branches: true
